-- This file is no longer used.
-- The database schema and all game data are now loaded automatically
-- from 'backend/main.py' and 'db/games.json' respectively!
-- You can safely delete this file, or keep it as a backup of your old SQL design.
